// Datos mock mientras configuramos Supabase

export const mockParcels = [
  {
    id: '1',
    code: 'HH-001',
    rol: '123-4567-8',
    surface_m2: 5000,
    price_uf: 3500,
    price_clp: 140000000,
    status: 'available' as const,
    water_source: 'apr' as const,
    water_details: 'APR Chicureo con factibilidad inmediata. Empalme incluido.',
    electricity: 'available' as const,
    internet: 'fiber' as const,
    buildable_summary: 'Parcela de agrado. Permitido construcción de hasta 2 viviendas unifamiliares. Coeficiente de constructibilidad 0.1.',
    max_construction_m2: 500,
    max_houses: 2,
    sag_conaf_restrictions: 'Área de protección de quebrada en sector norte (aprox 10% de la superficie). Requiere estudio de impacto ambiental para construcciones mayores a 300m².',
    location_lat: -33.1734,
    location_lng: -70.6486,
    slope: 'Pendiente suave (5-10%) orientación norte',
    is_verified: true,
    gallery: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200',
      'https://images.unsplash.com/photo-1464146072230-91cabc968266?w=1200',
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200'
    ],
    project: {
      id: 'proj-1',
      name: 'Hacienda Las Higueras',
      commune: 'Colina',
      region: 'Región Metropolitana',
      description: 'Exclusivo proyecto de parcelas de agrado en Chicureo. Entorno natural privilegiado con cercanía a colegios, centros comerciales y acceso directo a Ruta 5.',
      amenities: ['Portón de acceso', 'Caminos interiores', 'Áreas verdes', 'Vigilancia 24/7', 'Red de agua potable', 'Electricidad subterránea'],
    },
    financing_terms: {
      min_down_payment_pct: 20,
      monthly_interest_rate: 0.027,
      max_term_months: 60,
      amortization_type: 'french' as const,
      notes: 'Crédito directo sin pie adicional. Tasa fija durante todo el plazo.',
    }
  },
  {
    id: '2',
    code: 'HH-002',
    rol: '123-4567-9',
    surface_m2: 8000,
    price_uf: 5200,
    price_clp: 208000000,
    status: 'available' as const,
    water_source: 'well' as const,
    water_details: 'Pozo profundo existente con caudal de 2 lt/seg. Agua de excelente calidad.',
    electricity: 'nearby' as const,
    internet: 'signal' as const,
    buildable_summary: 'Parcela de agrado premium. Permitido hasta 3 viviendas. Mayor superficie edificable por ubicación.',
    max_construction_m2: 800,
    max_houses: 3,
    sag_conaf_restrictions: 'Sin restricciones SAG/CONAF. Zona libre para construcción.',
    location_lat: -33.1745,
    location_lng: -70.6495,
    slope: 'Plana con vista panorámica a la cordillera',
    is_verified: true,
    gallery: [
      'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200',
      'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=1200'
    ],
    project: {
      id: 'proj-1',
      name: 'Hacienda Las Higueras',
      commune: 'Colina',
      region: 'Región Metropolitana',
      description: 'Exclusivo proyecto de parcelas de agrado en Chicureo. Entorno natural privilegiado con cercanía a colegios, centros comerciales y acceso directo a Ruta 5.',
      amenities: ['Portón de acceso', 'Caminos interiores', 'Áreas verdes', 'Vigilancia 24/7', 'Red de agua potable', 'Electricidad subterránea'],
    },
    financing_terms: {
      min_down_payment_pct: 20,
      monthly_interest_rate: 0.027,
      max_term_months: 60,
      amortization_type: 'french' as const,
      notes: 'Crédito directo sin pie adicional. Tasa fija durante todo el plazo.',
    }
  },
  {
    id: '3',
    code: 'HH-003',
    rol: '123-4568-0',
    surface_m2: 3000,
    price_uf: 2400,
    price_clp: 96000000,
    status: 'available' as const,
    water_source: 'apr' as const,
    water_details: 'Conexión a APR con medidor individual incluido.',
    electricity: 'available' as const,
    internet: 'fiber' as const,
    buildable_summary: 'Parcela ideal para casa de fin de semana. Permitido 1 vivienda principal + 1 mediagua.',
    max_construction_m2: 300,
    max_houses: 1,
    sag_conaf_restrictions: 'Zona con presencia de flora nativa protegida. Se requiere mantener al menos 20% del terreno como área verde sin intervención.',
    location_lat: -33.1720,
    location_lng: -70.6470,
    slope: 'Leve pendiente sur (3-8%)',
    is_verified: false,
    gallery: [
      'https://images.unsplash.com/photo-1542224566-6e85f2e6772f?w=1200'
    ],
    project: {
      id: 'proj-1',
      name: 'Hacienda Las Higueras',
      commune: 'Colina',
      region: 'Región Metropolitana',
      description: 'Exclusivo proyecto de parcelas de agrado en Chicureo. Entorno natural privilegiado con cercanía a colegios, centros comerciales y acceso directo a Ruta 5.',
      amenities: ['Portón de acceso', 'Caminos interiores', 'Áreas verdes', 'Vigilancia 24/7', 'Red de agua potable', 'Electricidad subterránea'],
    },
    financing_terms: {
      min_down_payment_pct: 20,
      monthly_interest_rate: 0.027,
      max_term_months: 60,
      amortization_type: 'french' as const,
      notes: 'Crédito directo sin pie adicional. Tasa fija durante todo el plazo.',
    }
  },
]
