// Datos mock de leads mientras configuramos Supabase

export const mockLeads = [
  {
    id: '1',
    tenant_id: 'b0a1c2d3-e4f5-6789-0abc-def123456789',
    parcel_id: '1',
    project_id: 'proj-1',
    buyer_name: 'Juan Pérez',
    buyer_whatsapp: '+56912345678',
    buyer_email: 'juan.perez@email.com',
    budget_uf: 3800,
    payment_method: 'direct_credit' as const,
    simulated_monthly_payment_clp: 420000,
    intent: 'live' as const,
    decision_timeframe: '1_3_months' as const,
    score: 85,
    score_breakdown: {
      budget_match: 95,
      payment_clarity: 85,
      timeframe: 80,
      intent: 90,
      engagement: 75,
    },
    temperature: 'hot' as const,
    status: 'new' as const,
    assigned_to: null,
    notes: '',
    source: 'parcel_page' as const,
    created_at: '2026-06-22T10:30:00Z',
    updated_at: '2026-06-22T10:30:00Z',
    parcel: {
      code: 'HH-001',
      project: {
        name: 'Hacienda Las Higueras',
        commune: 'Colina',
      }
    },
    conversations: [
      {
        id: '1',
        role: 'buyer' as const,
        message: 'Hola, me interesa la parcela HH-001',
        created_at: '2026-06-22T10:30:00Z',
      },
      {
        id: '2',
        role: 'agent' as const,
        message: '¡Hola Juan! 👋 Qué bueno que te interese la parcela HH-001 en Hacienda Las Higueras. Es una parcela verificada de 5.000 m² en Colina. ¿Estás buscando para vivir o para invertir?',
        created_at: '2026-06-22T10:30:30Z',
      },
      {
        id: '3',
        role: 'buyer' as const,
        message: 'Para vivir, quiero construir mi casa',
        created_at: '2026-06-22T10:31:00Z',
      },
      {
        id: '4',
        role: 'agent' as const,
        message: 'Perfecto! Esta parcela permite construir hasta 2 viviendas con un máximo de 500m² edificables. ¿Tienes un presupuesto aproximado para la compra?',
        created_at: '2026-06-22T10:31:15Z',
      },
      {
        id: '5',
        role: 'buyer' as const,
        message: 'Tengo como 3800 UF ahorradas',
        created_at: '2026-06-22T10:32:00Z',
      },
      {
        id: '6',
        role: 'agent' as const,
        message: 'Excelente! Con 3.800 UF te da perfecto para esta parcela que vale 3.500 UF. ¿Pensabas pagar al contado o preferirías crédito directo?',
        created_at: '2026-06-22T10:32:20Z',
      },
      {
        id: '7',
        role: 'buyer' as const,
        message: 'Prefiero crédito para no descapitalizarme. ¿Cuánto sería la cuota?',
        created_at: '2026-06-22T10:33:00Z',
      },
      {
        id: '8',
        role: 'agent' as const,
        message: 'Con un pie del 20% (700 UF) y financiando 2.800 UF en 36 cuotas, tu cuota mensual sería de aproximadamente $420.000. ¿Te calza ese monto?',
        created_at: '2026-06-22T10:33:40Z',
      },
      {
        id: '9',
        role: 'buyer' as const,
        message: 'Sí, perfecto! Me gustaría visitarla este fin de semana',
        created_at: '2026-06-22T10:34:00Z',
      },
    ]
  },
  {
    id: '2',
    tenant_id: 'b0a1c2d3-e4f5-6789-0abc-def123456789',
    parcel_id: '2',
    project_id: 'proj-1',
    buyer_name: 'María González',
    buyer_whatsapp: '+56987654321',
    buyer_email: 'maria.gonzalez@email.com',
    budget_uf: 6000,
    payment_method: 'cash' as const,
    simulated_monthly_payment_clp: null,
    intent: 'invest' as const,
    decision_timeframe: 'immediate' as const,
    score: 92,
    score_breakdown: {
      budget_match: 100,
      payment_clarity: 95,
      timeframe: 100,
      intent: 85,
      engagement: 80,
    },
    temperature: 'hot' as const,
    status: 'contacted' as const,
    assigned_to: null,
    notes: 'Inversionista seria. Ya visitó otra parcela del proyecto.',
    source: 'parcel_page' as const,
    created_at: '2026-06-21T15:20:00Z',
    updated_at: '2026-06-22T09:15:00Z',
    parcel: {
      code: 'HH-002',
      project: {
        name: 'Hacienda Las Higueras',
        commune: 'Colina',
      }
    },
    conversations: []
  },
  {
    id: '3',
    tenant_id: 'b0a1c2d3-e4f5-6789-0abc-def123456789',
    parcel_id: '3',
    project_id: 'proj-1',
    buyer_name: 'Roberto Silva',
    buyer_whatsapp: '+56956781234',
    buyer_email: null,
    budget_uf: 2000,
    payment_method: 'direct_credit' as const,
    simulated_monthly_payment_clp: 280000,
    intent: 'second_home' as const,
    decision_timeframe: '3_6_months' as const,
    score: 58,
    score_breakdown: {
      budget_match: 70,
      payment_clarity: 65,
      timeframe: 50,
      intent: 60,
      engagement: 45,
    },
    temperature: 'warm' as const,
    status: 'new' as const,
    assigned_to: null,
    notes: '',
    source: 'whatsapp_search' as const,
    created_at: '2026-06-22T14:45:00Z',
    updated_at: '2026-06-22T14:45:00Z',
    parcel: {
      code: 'HH-003',
      project: {
        name: 'Hacienda Las Higueras',
        commune: 'Colina',
      }
    },
    conversations: []
  },
  {
    id: '4',
    tenant_id: 'b0a1c2d3-e4f5-6789-0abc-def123456789',
    parcel_id: '1',
    project_id: 'proj-1',
    buyer_name: 'Andrea Torres',
    buyer_whatsapp: '+56923456789',
    buyer_email: 'andrea.torres@email.com',
    budget_uf: null,
    payment_method: 'unknown' as const,
    simulated_monthly_payment_clp: null,
    intent: 'unknown' as const,
    decision_timeframe: 'exploring' as const,
    score: 25,
    score_breakdown: {
      budget_match: 0,
      payment_clarity: 0,
      timeframe: 20,
      intent: 0,
      engagement: 30,
    },
    temperature: 'cold' as const,
    status: 'new' as const,
    assigned_to: null,
    notes: '',
    source: 'parcel_page' as const,
    created_at: '2026-06-22T16:00:00Z',
    updated_at: '2026-06-22T16:00:00Z',
    parcel: {
      code: 'HH-001',
      project: {
        name: 'Hacienda Las Higueras',
        commune: 'Colina',
      }
    },
    conversations: []
  },
]
